---
:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  :release_build: TRUE
  :test_file_prefix: test_
  :which_ceedling: gem
  :ceedling_version: 0.31.1

:release_build:
  :output: embedded_project.out
  :use_assembly: FALSE

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/**
  :include:
    - include/**
  :support:
    - test/support

:defines:
  :common: &common_defines []
  :test:
    - *common_defines
    - UNIT_TEST
  :test_preprocess:
    - *common_defines
    - UNIT_TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8:    HEX8
    uint16:   HEX16
    uint32:   UINT32
    int8:     INT8
    bool:     UINT8

:gcov:
  :utilities:
    - gcovr           # HTML reports
    - ReportGenerator # alternative
  :reports:
    - HtmlDetailed
    - Text
    - JSON
  :gcovr:
    :report_root: "."
    :report_exclude: "^build|^vendor|^test"
    :html: true
    :html_details: true
    :html_medium_threshold: 75
    :html_high_threshold: 90
    :print_summary: true

:tools:
  :release_compiler:
    :executable: gcc
    :arguments:
      - -c
      - -std=c11
      - -pedantic
      - -Wall
      - -Wextra
      - -Werror
      - ${1}
      - -o ${2}
      - -I"$": COLLECTION_PATHS_SOURCE_INCLUDE_VENDOR
      - -I"$": COLLECTION_PATHS_RELEASE_TOOLCHAIN_INCLUDE
  :release_linker:
    :executable: gcc
    :arguments:
      - ${1}
      - -o ${2}

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
